### ISSUE TITLE
Dog character overlayed

### ISSUE THREAD

**Issue by oanarosca** [fossasia/flappy-svg#239]
As you can see in the picture below, the dog character is not marked as a hidden layer in the flappy.svg file, and so it appears on top of the others, even during the game. I could easily fix it myself, but I think it would be a good issue for new contributors.
![screenshot from 2016-12-30 23-27-41](https://cloud.githubusercontent.com/assets/3405816/21572979/34008718-cee8-11e6-8728-7fa843b334ca.png)

**Comment by Marauderer97** [comment]
Isn't the dog character reachable via clicking on the characters, I tried reaching it but couldn't?

**Comment by Abhi2424shek** [comment]
@Marauderer97 do you want to work for it if yes then please open a separate issue for the same and deliver a PR

**Comment by Marauderer97** [comment]
@Abhi2424shek I just made a PR, there were a few other minor changes, made them too. Please review.
P.S For some reason all my previous commits appear with each PR, I cannot find a way to fix it, and squashing it is leading to weird errors. I branch from gh-pages,  yet this happens, any suggestions about this would be appreciated.

**Comment by niccokunzmann** [comment]
@Marauderer97 This is what I would try for removing unwanted commits:

1. You can check out a commit that is also in this repository (e.g. the last commit there). `git checkout <numbersandletrers>`
2. You create a new branch `git checkout -b branchname`
3. You cherry-pick the commits you like to have there: `git cherry-pick <numbersandletters>`
4. You push it
5. You create a pull-request

**Comment by Marauderer97** [comment]
@niccokunzmann Thanks! Have been struggling with this for a while now! :+1:

**Comment by Abhi2424shek** [comment]
@marauderer97 if you are struggling here's a hint: you need to make the dog elements display: none using JavaScript just like other characters in the game :)

**Comment by Marauderer97** [comment]
@Abhi2424shek you have the context wrong, i was talking about help with the squash and merge.. i think this particular bug has been fixed long back.

**Comment by Abhi2424shek** [comment]
I was talking on how to resolve the issue, @marunderer97 this issue is not fixed yet.

**Comment by Marauderer97** [comment]
Closing the issue to avoid confusion. This bug had been fixed a while ago.. not sure by whom.

**Comment by Marauderer97** [comment]
@Abhi2424shek  are u sure? Tge issue looks fixed to me.

**Comment by Marauderer97** [comment]
Oh my bad.. there seems to be an issue only when camel is selected.. yeah its pretty straightforward I think we should leave this for new comers.

**Comment by Abhi2424shek** [comment]
Really sure, just see the current screenshots: (Not only for camel)
![image](https://cloud.githubusercontent.com/assets/8947010/21747710/69fbf06e-d596-11e6-8e92-15eb0d3040a4.png)

**Comment by Marauderer97** [comment]
@Abhi2424shek okay, I get it now, once the dog gets displayed, its visibility is never set back to none, yeah, I can of course fix this pretty easily but like already stated, I think this bug will be good for newcomers. If you think its already been too long go ahead and make a PR :)

**Comment by Abhi2424shek** [comment]
@Marauderer97 I leave it for newcomers :)
